#!/bin/bash

cd ./build/libs/
rm *-sources.jar
rm *-dev.jar
FILE_NAME=`echo disfabric-*`
cd ../../
FILE_LOCATION=`echo "./build/libs/$FILE_NAME"`
CHANGE_LOG=`git log -1 --pretty=format:"%B"`

#See https://github.com/curseforge/api for how to retrieve game version numbers
JSON=`printf '{"changelog": "%s", "gameVersions": [7499,7892,8010,8056,8134], "releaseType": "release"}' "$CHANGE_LOG"`

echo "Uploading $FILE_NAME to Curse Forge..."
echo
RESPONSE=`curl -H "X-Api-Token: $CURSE_API_KEY" -X POST  -F metadata="$JSON"  -F file="@$FILE_LOCATION" https://minecraft.curseforge.com/api/projects/399520/upload-file`
echo
echo $RESPONSE
